### ISSUE TITLE
External Engagement: Excel Sheet Upload

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#11]
- The option to download the formatted sheet and upload needs to be added. I have added the formatted sheet to this issue.
- Then, the feature to upload will need to calculate the numbers and populate Template D. 

[External_Engagement_Reporting_Sheet.xlsx](https://github.com/EPSCoR/ercore8/files/1881859/External_Engagement_Reporting_Sheet.xlsx)

**Comment by ercore** [comment]
@tschet please update content type title to read **ER Core External Engagement Event**

Also, I do not have the spreadsheet available for download/upload.

**Comment by ercore** [comment]
@tschet the EE spreadsheet still needs to be added.

**Comment by tschet** [comment]
![screenshot-drupalvm test-2018 07 15-16-00-45](https://user-images.githubusercontent.com/1022202/42738365-51c6dd7c-8848-11e8-9c0c-546a121b069d.png)
The link show above doesn't work for you?

**Comment by ercore** [comment]
@tschet it's not there.

This is what I see.

![screen shot 2018-07-16 at 11 19 24 am](https://user-images.githubusercontent.com/8887329/42773364-3fd03d1e-88ea-11e8-856f-cb3895b3cdde.png)

**Comment by ercore** [comment]
@tschet I now see the spreadsheet and manually entry area. 

Now I am having a hard time getting passed the Time requirement, in the Start and End date fields. It will not accept any values I enter. 

![screen shot 2018-07-16 at 12 27 12 pm](https://user-images.githubusercontent.com/8887329/42776384-08073a18-88f4-11e8-8e3d-4ee0a4d0e29e.png)

**Comment by ercore** [comment]
@tschet never mind, I figured out that the last two digits/characters are for AM/PM.

**Comment by ercore** [comment]
@tschet 
- I downloaded the sheet, filled it out, and ticked the box that said “tick this if you want to be able to edit the sheet”. But I cannot edit the sheet. the option to upload has disappeared.

![screen shot 2018-07-16 at 1 37 01 pm](https://user-images.githubusercontent.com/8887329/42779987-46a3b03e-88ff-11e8-94b1-6cc6889eb38f.png)

**Comment by ercore** [comment]
@tschet 

- I am able to upload and remove sheet
- Manual entry works even after uploading a sheet
**- The sheets counts do not transfer to the EE view/page**
- It looks like the numbers are populating Template D

**Comment by tschet** [comment]
It appears to be working to me. I'll take a shot at updating the instructions for clarity. the key bit I haven't clarified is that uploading the PDF doesn't trigger the tabulation of numbers. Saving the node does. So you can't check the box before saving the node.

**Comment by ercore** [comment]
@tschet okay, I am putting this back in the In Progress column.

**Comment by tschet** [comment]
Why are you putting it back in progress?

**Comment by ercore** [comment]
Because  you are still working on it? Also, can you show me how it is working for you?

**Comment by tschet** [comment]
I've updated the field help text to try to clarify the way it works.

**Comment by ercore** [comment]
@tschet the issue with this is that the totals are not being reflected on the nodes view. See attached screenshot from your Engagements entry. They do show when you manually enter the numbers but not when you upload the spreadsheet. We need them to reflect what is in the spreadsheet.
<img width="695" alt="screen shot 2018-07-24 at 9 36 59 am" src="https://user-images.githubusercontent.com/8887329/43149818-a99ab620-8f25-11e8-853c-43e2f41feb72.png">

**Comment by tschet** [comment]
Ah. My code that was calculating fields values after file upload was running after calculating totals. I fixed that. 
It was actually working (sort of) if you re-saved the node a second time. Which apparently I did when testing, without realizing the totals didn't appear until the second save.
Now it should calculate on the first save, as expected.

**Comment by ercore** [comment]
@tschet Looks like it's working!

Closing this one.
