### ISSUE TITLE
External Engagement: Manual Entery Fields

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#12]
Please update all the fields to be **Not Required**.

**Comment by tschet** [comment]
That makes the the form's code infinitely more complex. Currently it is required, but defaults to 0. Unless someone removes a value and leaves it empty, the required aspect will never be an issue.

**Comment by ercore** [comment]
From a usability standpoint, the red asterisks indicates that the field is required and if they are not then it's just confusing. If these fields are actually not required then can you hide them?

**Comment by tschet** [comment]
Yes, we should be able to hide the red asterisk fairly easily, and we can add a description to indicate that all fields must be filled.

**Comment by ercore** [comment]
Please note that All fields Do Not Need To Be Filled Out. It is dependent on how many people attend an event. We can talk to confirm/clarify this.

**Comment by tschet** [comment]
That should be correct. I’m not suggesting they need to have numbers added. It just becomes significantly more difficult to process the data from all those fields when you add into the mix that the field may be 0, a positive number, or NULL. If the field is not set to required, the zero can be removed, setting the value to NULL.
