### ISSUE TITLE
User Profile: "Changes have been saved" text

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#14]
After saving updates in the user profile there's no notification that the information entered has been saved. Please add this otherwise it is confusing. See attached example from D7 version.

<img width="300" alt="changes have been saved" src="https://user-images.githubusercontent.com/8887329/39539784-e2b45cc2-4dfd-11e8-8a4e-ad121b9df0ea.png">

**Comment by tschet** [comment]
That's theme specific, the message is being generated as expected, some themes display, but not all display the same.

**Comment by ercore** [comment]
I see no message at all, perhaps the browser I am using? We need a visible message to generate.

**Comment by ercore** [comment]
@tschet we talked about this update during our last call. Please have this feature implemented by default for all installations.

**Comment by ercore** [comment]
@tschet This is has been updated. Moving to Done.
