### ISSUE TITLE
Most Senior Project Roles Updates

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#15]
- [x] **This Faculty part has been updated**
**Faculty Participant (or equivalent)**
Add:
- Components/Taxonomy
Take Out:
- Education and CERTIFICATIONS AND SUPPORTING DOCUMENTS headers

- [x] **This Technical Support Staff part has been updated**
_**Technical Support Staff**
Add:
- Components/Taxonomy
Take Out:
- Education and CERTIFICATIONS AND SUPPORTING DOCUMENTS headers_

- [x] **Non-technical Support Staff**
Add:
- Components/Taxonomy
Take Out:
- I am on the EPSCoR Management Team
- Education and CERTIFICATIONS AND SUPPORTING DOCUMENTS headers

- [x] **This Post Doc part has been updated**
_**Post Doc**
Add:
- Mentoring Plan Sign Off Date and Upload (see attached screenshot from D7 version).
<img width="771" alt="mentorting plan for post doc profile" src="https://user-images.githubusercontent.com/8887329/39540662-88c65302-4e00-11e8-92eb-73fe167158be.png">
Take Out:
- CERTIFICATIONS AND SUPPORTING DOCUMENTS_

- [x] **This Section has been updated**
_**Graduate Students**
Add:
- Additional set of education dates for Doctoral degrees. Anticipated Doctoral Graduation Date and Actual Doctoral Graduation Date_

- [x] **Undergraduate Students**
- This role is good, no changes

**Comment by ercore** [comment]
@tschet have you started on this one yet?

**Comment by tschet** [comment]
I’ve cleaned up a bunch of things related to this, but haven’t addressed these specific items yet. Fieldsets with no visible fields should disappear, but there’s a long standing bug associated with them being visible. I was planning on addressing this when other User fields were finalized, as field changes can affect this.

**Comment by tschet** [comment]
I believe I've addressed all of these, but it's convoluted to test, so I may have missed something.

**Comment by tschet** [comment]
I believe I've addressed all of these, but it's convoluted to test, so I may have missed something.

**Comment by ercore** [comment]
@tschet the only item left on this list is the following.

- For **Non-Technical Support Staff**
Take Out: I am on the EPSCoR Management Team

**Comment by ercore** [comment]
@tschet this has not been resolved. 

For Non-Technical Support Staff
Take Out: I am on the EPSCoR Management Team

<img width="405" alt="screen shot 2018-07-25 at 9 36 47 am" src="https://user-images.githubusercontent.com/8887329/43211353-90387018-8fee-11e8-9f02-cb0983f2dc5e.png">

**Comment by tschet** [comment]
I made in not required,  but missed visibility. Fixed

**Comment by ercore** [comment]
This has been resolved.
