### ISSUE TITLE
Presentations

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#19]
- Require the date field,
-  there’s Programs text box vs. a Programs selector? 
- Again, Program selector but no Components selector.

**Comment by ercore** [comment]
@tschet Components selector need to be added.

Moving this back to In Progress.

**Comment by ercore** [comment]
@tschet there's a Status field, which is not on the original version. At least not on http://dev-ercore.nmepscor.net. or on the NM Reporting site. Is this an error or flow over from another jurisdictions customization? Either way, I don't think we need it so please take it out.

**Comment by tschet** [comment]
I just pushed an update to the Presentation node type to add Components field

**Comment by ercore** [comment]
@tschet a few questions

1. The External Engagement Reporting sheet is under the title. Take it out.
2. The Status field (see screenshot)is not in the older version and I cannot find any documentation from the ThinkTank or requirements docs so I am wondering where this came from. Please check your notes and if there's reason or something documented to add it, we can keep it. If not, please delete it. Add documentation justifying that addition here. 
3. The wording on the text box, under the Components option field, needs to be updated to, "What is the name of the event (if any) where you presented?"
![presentationsstatus](https://user-images.githubusercontent.com/8887329/42709460-da3d058e-869d-11e8-92e7-647191b71dca.png)

**Comment by tschet** [comment]
1. fixed
2. hm, don't know where that came from. Must have crossed config at some point and duplicated s field. Removed in code, will remove on test site shortly.
3. Fixed in code, will deploy to test shortly.

**Comment by ercore** [comment]
@tschet 

- Move Programs and Components to the bottom of the page, above the Published checkbox.

**Comment by ercore** [comment]
This has been resolved.
