### ISSUE TITLE
Contact Information Updates

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#2]
1. Rename the following fields
- **Given** to **First Name**
- **Family** to **Last Name**

2. Add the following fields
- Primary Email Address (required)
- Secondary Email Address (not required)

**Comment by tschet** [comment]
When I initially started using the name field module in D7, is wasn't easy to change those field labels. I was pleased to see that they've fixed that in D8. This change will be done in this weekend's update.

**Comment by ercore** [comment]
Take out **Credentials** and **Employee ID**

**Comment by ercore** [comment]
Has this been updated to exclude the Credentials and Employee ID fields?

**Comment by ercore** [comment]
@tschet Take out Employee ID.

**Comment by ercore** [comment]
@tschet 

1. Take out Employee ID
2. Make Secondary Email required

**Comment by tschet** [comment]
Employee ID is widely used. It's easy to remove or hide a field that you don't want to use, and more difficult to add a field after ERCore is installed. We should leave this field in and jurisdictions that don't want to use it can easily hide it.
Making secondary email address required will cause problems. First it makes the assumption that users have two email addresses, which is not valid. Second, even users who have a second email address may not want to give a private email for purposes like this.

**Comment by ercore** [comment]
@tschet the secondary email was a request, I believe, from the Think Tank. Most undergrad and graduate students do have two email addresses. Leave as is for now and each jurisdiction can customize as needed.
Regarding Employee ID, we cannot use one because we work with multiple institutions. We will hide it.
