### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#21]
- Add DOI text field, titled "DOI" 
- Again, it has Programs but not Components

**Comment by ercore** [comment]
@tschet This has not been completed. Please add a DOI text filed and the Components selector.

**Comment by ercore** [comment]
@tschet DOI has been added but the content type is lacking the following.

- Components selector
- Make the **Peer Reviewed** box (for all publication types) **Required**

**Comment by ercore** [comment]
@tschet the above items have been completed but I found a few more issues.

1. Take out Publication Information header (see screenshot) on Abstract, Thesis Dissertation, and Internet Dissemination options.
![publicationinformationheader](https://user-images.githubusercontent.com/8887329/42710008-9889aba4-869f-11e8-9366-26c879e25662.png)

2. Take out, External Engagement Reporting Sheet download

**Comment by tschet** [comment]
Both items on this were fixed earlier this week.

**Comment by ercore** [comment]
@tschet everything looks good on this content type. It is also populating Template E! That's good.

Though, can  you please move the Component and Program fields to the bottom, right above the Published check box? Currently they show up right below the Publication Type. 

Thanks!

**Comment by ercore** [comment]
This has been resolved.
