### ISSUE TITLE
Components and Programs changes

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#25]
Components and Programs need to be moved from the Institutions tab to the EPSCoR Involvement tab.

**Comment by tschet** [comment]
Happy to move those, but it seems counter intuitive. Feels like the programs would be associated with the institution rather than EPSCoR

**Comment by ercore** [comment]
I am still unsure where programs came from. We do not have this option in NM and was not in the last version. In the last version we had Departments. Maybe that was changed in another version you were referring to? Either way, Components needs to be moved to the EPSCoR involvements tab.

**Comment by tschet** [comment]
No, you're right. It just seems odd to me. Fixing.

**Comment by ercore** [comment]
Is programs part of another custom site you worked on? Maybe ND? If I can get an explanation as to why it's there then I can understand how to use it.  I just don't understand how it's supposed to be used.

**Comment by tschet** [comment]
Fixed.

**Comment by ercore** [comment]
Can you please track down where Programs came from? Maybe it was Departments before Programs?

**Comment by tschet** [comment]
The name it’s called varies across sites, but the field is the same. Some sites use both programs and components, some use one.

- Douglas

**Comment by ercore** [comment]
Can you also make Component required?

**Comment by ercore** [comment]
@tschet one more update and this will be done. Also, this is happening on other content types.

- Update Programs and Components to have a dropdown/options selector vs auto populate. And, move it to the bottom of the page.

Update this:
![screen shot 2018-07-18 at 4 27 43 pm](https://user-images.githubusercontent.com/8887329/42911971-5cf52fd2-8aaa-11e8-9b10-68b3e9925f72.png)

To this:
![screen shot 2018-07-18 at 4 41 02 pm](https://user-images.githubusercontent.com/8887329/42911980-622acc14-8aaa-11e8-8992-9aab125d3ffe.png)

**Comment by ercore** [comment]
This has been resolved.
