### ISSUE TITLE
Error when trying to download Accomplishments Tables and Individual Tables

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#26]
I am getting the following error when trying to download the Accomplishments Tables and Individual Tables.

The website encountered an unexpected error. Please try again later.

**Comment by tschet** [comment]
This has been resolved. My local environment was forgiving a capitalization error it should not have been. Yours was correctly throwing the error.

**Comment by ercore** [comment]
@tschet it is downloading but the output it gibberish.  See screen shot

<img width="718" alt="screen shot 2018-07-06 at 5 06 18 pm" src="https://user-images.githubusercontent.com/8887329/42403569-4bdbbd3e-813f-11e8-953a-2407a533784b.png">

**Comment by ercore** [comment]
@tschet This is the message from Excel before opening the sheet.

![screen shot 2018-07-09 at 1 57 14 pm](https://user-images.githubusercontent.com/8887329/42475849-2f8e139c-8389-11e8-8e94-40937f652b39.png)

**Comment by tschet** [comment]
This is hard to replicate, but I believe I have resolved it.

**Comment by ercore** [comment]
Your fix worked!

**Comment by ercore** [comment]
This has been resolved.
