### ISSUE TITLE
Education and Certs header showing up on unnecessary roles

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#27]
The Education and Certificates headers are showing on roles that do not need them.

The roles are and the header:
- Faculty = EDU + Cert
- Technical Support Staff = Certs
- Non-Technical Support Staff = EDU + Certs
- Post Docs = Certs

Here's a screen shot of the headers.
<img width="859" alt="screen shot 2018-07-06 at 4 30 34 pm" src="https://user-images.githubusercontent.com/8887329/42403087-020d89f6-813c-11e8-9ab9-8d858b96c904.png">

**Comment by tschet** [comment]
fixed on github, pushing to site later today

**Comment by tschet** [comment]
ready for review

**Comment by ercore** [comment]
This has been resolved.
