### ISSUE TITLE
Demographics Updates

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#3]
1. Make the Demographics Tab Required by adding a red asterisk to the tab
2. Add option to the bottom of the page, **Prefer not to answer**

**Comment by ercore** [comment]
Prefer not to answer has been added.
Still need to add **red asterisk to the tab.**

**Comment by tschet** [comment]
Set the demographics fields to required, and disable with prefer not to respond.

**Comment by ercore** [comment]
@tschet, We cannot make each individual field required in the Demographics section, which is why we requested that a red asterisk be added only to the tab.

Please retain the red asterisk in the tab but take out the requirement on each individual demographic field.

**Comment by tschet** [comment]
Before I make any more changes here, I'd like to have a complete plan on what we intend to do here. I keep thinking we have come to resolution, I make changes, and the goal line moves.

My understanding was that we would make the fields required, with a checkbox at the end of the tab for users who don't want to respond. If the questions aren't required, what's the purpose of I don't want respond field? The field adds significant complexity with not benefit of the fields are all optional.

**Comment by ercore** [comment]
@tschet this has been controversial since the beginning. We cannot, by law, require people to answer this question. The compromise wast to add the Prefer Not To Answer, at the bottom, and add the red asterisk to the tab only. If you would like, we can wait on this update to ask the group at the next meeting. The next meeting is scheduled for Tuesday July 24th at 2:00pm MT.

**Comment by tschet** [comment]
The "Prefer Not To Answer" disables the fields and removes the requirement. If they aren't required, the "Prefer Not To Answer" checkbox serves no purpose.

**Comment by ercore** [comment]
@tschet we can release like this and update later if needed.
