### ISSUE TITLE
Template E: Outputs: Graduate/Undergraduate/Post Doc issue

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#30]
@tschet Template E Outputs is not recognizing **Hispanic or Latino** as **Underrepresented Minority**
- It should populate in the Underrepresented Minority cell when Hispanic or Latino is ticked in the demographics tab.

**Comment by tschet** [comment]
This should have been addressed with my last update.

**Comment by ercore** [comment]
@tschet this looks like it has been resolved.
