### ISSUE TITLE
Template E: Outputs: Patents Current Yr and Cummulative #s

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#31]
@tschet it looks like the current and cumulative #s are switch in the Patents section of Template E.

- I add two tests, one in the first year and the other in the current year. 
- Both populate in the current column and one in the cumulative. See this page, http://129.24.196.219/ercore/admin-views/outputs

**Comment by tschet** [comment]
I have not tested this yet, but two things come to mind.

1. I did find a bug in my table E code, which is now fixed.
2. It is possible to add event dates outside the scope of "cumulative", but within the selected range. This can be done for instance by adding an event (or other node type) with the date field set before the grant's start date, and selecting a date range that includes that date. I'm not suggesting this is what you're seeing, but that it can be done.

**Comment by tschet** [comment]
More involved than I'd hoped, but I believe resolved

**Comment by ercore** [comment]
@tschet can you please test this. It looks like the 2017 to 2018 date range is correct but not the 2018 to 2019 range. Please test to confirm this template is populating correctly.
http://129.24.196.219/ercore/admin-views/outputs

**Comment by tschet** [comment]
What are you seeing wrong?

**Comment by ercore** [comment]
@tschet shouldn't Cumulative be greater than Current. With the exception of year one? In year one, they would be the same. Currently, Current is larger than Cumulative.

**Comment by tschet** [comment]
They are equal or cumulative is bigger in my testing for various time ranges.

**Comment by ercore** [comment]
@tschet looks like this has been resolved! Thanks!
