### ISSUE TITLE
ER Core Content View Exports

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#37]
Currently, all exports on this page, http://129.24.196.219/ercore/content, are .cvs please update to export as excel spreadsheet. The latest version would be ideal.

**Comment by tschet** [comment]
I can switch those views to export in Excel, but it requires a dependency on a Drupal module and an associated library which are both deprecated.

**Comment by ercore** [comment]
So you can switch but it won't work because the associated module and library is depreciated? Or will it work if you switch?

**Comment by tschet** [comment]
Leaving as CSV for now
