### ISSUE TITLE
ER Core Data Integrity with Exclude from Reporting option

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#38]
The data integrity view was a request from the Think Tank and meetings before the Think Tank. Look here, http://dev-ercore.nmepscor.net./admin/epscor/views/check, for details.

**Comment by tschet** [comment]
Can I be made an admin of http://dev-ercore.nmepscor.net. so I can view the details of this view and others?

**Comment by ercore** [comment]
You now have administrative access.

**Comment by ercore** [comment]
Below is a list of all the content types/things to check in the data integrity view (from D7 site). As we discussed, there may be some changes in D8 that fixed some of these checks or now make them irrelevant. Please double check to make sure though.
 
**Collaborations:**
- no names
- no end date
**External Engagement:**
- No data attached
- zero count
- event repeats
**Proposals and Grants:**
- no status update
**Highlights:**
- Missing date
**Publications:**
- no status
**Presentations:**
- missing date
**Other research product:**
- missing date

**Comment by ercore** [comment]
Moved to ER Core D8 Maintenance Board. https://trello.com/c/wqoHKPPN
