### ISSUE TITLE
EPSCoR Involvement Updates

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#4]
As stated in Issue #1, the Most Senior Project Role needs to be moved to the EPSCoR Involvement Tab, as well as the Participation Dates field. 

The Most Senior Project Roles determine what is shown on the EPSCoR Involvement tab. Please refer to http://dev-ercore.nmepscor.net./ to see the differences between the roles as well as the ER Core D8 Trello board to see updates/changes recorded from the Think Tank. Here are two specific to Graduates https://trello.com/c/5G9oWwyY and Faculty https://trello.com/c/jqAHYSAk

**Comment by ercore** [comment]
Participant Dates Notes:

- add the option to add multiple participant dates to a participant. Do not allow for a specific date or start end date, only an award year. Example: Joe in year 1 was an undergraduate student, in year 2 his role changed to graduate student.

- Could this be an additional field/option only for PI/Admin Staff/reporter?

**Comment by tschet** [comment]
The move part is done, the multiple values is not

**Comment by tschet** [comment]
Moving the field to EPSCoR tab and allowing for multiple participation dates are not related at all. Can we split this issue into two?

**Comment by ercore** [comment]
@tschet yes, I will create another issue for the multiple participation dates and close this one.
