### ISSUE TITLE
ER Core Custom Views Link

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#40]
In the ER Core Admin Menu, add a link to Custom Views.

**Comment by tschet** [comment]
What custom Views am I linking to? I  think I'm misunderstanding this one.

**Comment by ercore** [comment]
@tschet add link to the ER Core Admin Menu (see attached screenshot). List out custom links, similar to the ER Core Content links page.
![screen shot 2018-08-23 at 12 49 20 pm](https://user-images.githubusercontent.com/8887329/44545798-42926200-a6d3-11e8-86a7-53f0b24dc061.png)

**Comment by ercore** [comment]
This is done.
