### ISSUE TITLE
Accomplishments table time range not detecting future entries

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#43]
@tschet the Accomplishments tables are not detecting when a future entry in added. I have added nodes with dates of 2020 but they are not showing up in the Accomplishments drop down or associated template views. See attached screen shot.

![screen shot 2018-07-31 at 3 24 52 pm](https://user-images.githubusercontent.com/8887329/43835662-f70bcdb2-9acf-11e8-8951-2f5ad77038aa.png)

**Comment by tschet** [comment]
Is there an appropriate date range to use as a default? Currently it uses the grant date as the start date and one year from "today" for the end date if no range is chosen.

**Comment by ercore** [comment]
It should use the award date range. So if an award starts June 1, 2018 the end date for that 1st year and every year after that will be May 31, 2018. 

Also, you need to make sure that the reporting month can change too. The first year of reporting usually aligns with the award year, though the second year and years after may change. Please look here http://dev-ercore.nmepscor.net./admin/config/epscor/er to review. Notice on this page that there are two options for dates, the **Start Date of EPSCoR Grant: ** and the **Reporting Period starting month: **

Let me know if we need to talk about this. It's complex but it important to get it correct.

**Comment by ercore** [comment]
@tschet per the Admin meeting today, they want to retain the Accomplishments table. For our next call, we can outline what that should look like for D8. Would that be helpful?

**Comment by tschet** [comment]
Defined end date ERCore admin http://129.24.196.219/admin/config/ercore/adminsettings now has fields to defined end date. Tier, extension, etc.

**Comment by ercore** [comment]
@tschet I get the following error when clicking on the Accomplishments link.

"The website encountered an unexpected error. Please try again later."

**Comment by tschet** [comment]
Fixed.

**Comment by ercore** [comment]
@tschet the custom date range is working but I still am not seeing the future reporting years. See screenshot. It is now reduced to only one reporting year even though there's data in there for yr 2. 
<img width="360" alt="screen shot 2018-09-06 at 5 57 37 pm" src="https://user-images.githubusercontent.com/8887329/45191124-ab62f980-b1fe-11e8-9934-e728a7383246.png">

**Comment by ercore** [comment]
@tschet if you have a few minutes tomorrow, maybe we can talk about it?

**Comment by tschet** [comment]
I think I've been misunderstanding what you're looking for.  So we're expecting to see future reporting periods?

**Comment by ercore** [comment]
Yes, as well as past. We should be able to toggle between all reporting years. That is, if there's data in those years. Here's a screenshot of the NM reporting site. We have data that goes out to 2020. When I select one of those years, I can then download those sheets/templates and they will be populated with that particular years data.
<img width="299" alt="screen shot 2018-09-06 at 6 15 02 pm" src="https://user-images.githubusercontent.com/8887329/45191515-efef9480-b200-11e8-8f1b-0049f6745664.png">

**Comment by tschet** [comment]
I believe this is working as discussed.

**Comment by ercore** [comment]
Yes! It looks like it is working now.
