### ISSUE TITLE
Links missing on ER Core Content Views

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#44]
@tschet all the links have disappeared on this page, http://129.24.196.219/ercore/content

**Comment by tschet** [comment]
I rebuilt the menu and they reappeared. It seems to have cached incorrectly, or something similar.

**Comment by ercore** [comment]
@tschet the links are back. Though, the downloads need to be excel files and not cvs files. I created a separate issue for that here, https://github.com/EPSCoR/ercore8/issues/37

**Comment by ercore** [comment]
@tschet for some reason, these links have disappeared again.

**Comment by tschet** [comment]
Fixed? they were working for me, but I rebuilt the menu just in case.

**Comment by ercore** [comment]
They are back!
