### ISSUE TITLE
EPSCoR Involvement: Boards and Committees

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#6]
Take out the options/choices (External Advisory Board, State EPSCoR Committee, RII4 Management Team). These options are NM specific but should change for each jurisdiction, if they choose to use this feature. Also, if this feature is used, it should only be viewable/available to Faculty Researcher and Admin Staff/PIs.

**Comment by tschet** [comment]
I changed this to an entity reference so that each jurisdiction can add their own values.

**Comment by ercore** [comment]
Great! Closing this issue.
