### ISSUE TITLE
Add User

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#7]
Please duplicate what the current ER Core **add user** does.

**Fields:**
First Name
Last Name
Username
E-mail address

**For the password fields, configure so that the person entering the user does not have to create a password.**

Auto check "Notify user of new account"

**Comment by ercore** [comment]
If you can, please take out the **Credentials Field**.

**Comment by ercore** [comment]
I still see the **Credentials** field in the Add User page. Can it be removed?

**Comment by tschet** [comment]
I just pushed the updated version which should have dropped the credentials field.

**Comment by ercore** [comment]
@tschet there are a few items that have not been updated.

- **For the password fields, configure so that the person entering the user does not have to create a password.**
- Notify user of new account, should be ticked by default.

**Comment by ercore** [comment]
@tschet **Again, the following updates have not been made.**

- **For the password fields, configure so that the person entering the user does not have to create a password.**
- **Notify user of new account, should be ticked by default.**

**Comment by tschet** [comment]
Changes made on github, I'll update the site later today.

**Comment by tschet** [comment]
Changes have been made

**Comment by ercore** [comment]
@tschet This works now. Thanks!
