### ISSUE TITLE
Collaborations: End Date

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#8]
Ending a Collaboration changes from jurisdiction to jurisdiction so please do not make this required.

**Comment by ercore** [comment]
@tschet a few things need to be updated here.
- It is still requiring an end date. We cannot require an end date because some collaborations never end.
- In the External Collaborations field, Institution/organization, it is only allowing Participating Institutions (Institutions that are already in the system). This field needs to allow for both External and Internal/Participating Institutions. Perhaps add another field for External Institutions? This field should be required too.

**Comment by ercore** [comment]
@tschet These updates have not been completed and I've added a third item.

1. It is still requiring an end date. We cannot require an end date because some collaborations never end.
2. In the External Collaborations field, Institution/organization, it is only allowing Participating Institutions (Institutions that are already in the system). This field needs to allow for both External and Internal/Participating Institutions. 
3. The External Engagement sheet is available below the Collaboration title. This needs to be removed. See screenshot 

![collaborationsscreenshot](https://user-images.githubusercontent.com/8887329/42707236-ce313cee-8696-11e8-99c0-3a3e7f0fb5ca.png)

**Comment by tschet** [comment]
Hm. The closing date isn't actually required, but the validator is misreading the empty date as earlier than the start date. Same result, but different cause. Fixing.

**Comment by tschet** [comment]
Should be working.

**Comment by ercore** [comment]
@tschet  the end date issue has been resolved but the following has not.

- In the External Collaborations field, Institution/organization, it is only allowing Participating Institutions (Institutions that are already in the system). This field needs to allow for both External and Internal/Participating Institutions.

![screen shot 2018-07-16 at 11 29 59 am](https://user-images.githubusercontent.com/8887329/42775578-f4d6efbc-88f1-11e8-95b0-857e6646ad59.png)

**Comment by tschet** [comment]
This is allowing non-participating institutions and has been for some time. The error above is that there isn't an institution in your test site with that name.

**Comment by ercore** [comment]
@tschet ideally, the non-participating institution should be initiated here, in this window, since we do not know who or what kind of institution that is until the Participant enters it. Does that make sense?

**Comment by ercore** [comment]
@tschet also, in the D7 version, we show all institutions to the user that are already in the system + a smart form if your institution is not in the list. This eliminates the potential for duplicates. Can we do this? 

Here's a screenshot of the D7 form:
![screen shot 2018-07-19 at 9 28 23 am](https://user-images.githubusercontent.com/8887329/42952682-45701322-8b36-11e8-9614-a131b0d27f02.png)

**Comment by ercore** [comment]
@tschet have you reviewed my latest comment on this?

**Comment by tschet** [comment]
I was in the process of adding a comment to this when it locked me out last week.

I would rather add that functionality as an add-on if possible. About half of the sites I work on don't allow non-admin users to add institutions, which makes it necessary to disable this bit. This can be awkward if it's hard-coded in the module.

**Comment by ercore** [comment]
@tschet yes, we do not allow participants to add institutions either which is why the D7 version allows you to pick an existing institution. And if your institution is not listed then you add it. Though, when it's added the admin vets it and they are the ones who categorize it. This is a pretty important step considering a collaboration only counts if it has external collaborators. We may need to talk through this one.

**Comment by tschet** [comment]
There's a link under the Institution field for adding an institution. It doesn't currently autofill the field when you add an institution. There are several modules in Drupal 7 for adding nodes/terms like this, but none of them have been ported to Drupal 8 completely yet. One of them was ported, but it doesn't work in this context.

**Comment by tschet** [comment]
As I mentioned, it doesn't autofill, but it allows you to add an institution that is immediately available in the auto complete.

**Comment by ercore** [comment]
@tschet Collaborations appear to be populating the template correctly. I think the UI can be refined, specifically when adding an external collaborating institution but we will have to work on that at a later time. It is definitely better than the last version.

One more request for this content type. The window that opens when adding an institution that is not listed is small, can you please make it wider? See attached image.
<img width="485" alt="screen shot 2018-08-08 at 6 44 51 am" src="https://user-images.githubusercontent.com/8887329/43838396-76dea098-9ad8-11e8-8476-83f6132728c2.png">

**Comment by ercore** [comment]
@tschet were you able to make the Create ER Core Institution popup window wider?

**Comment by tschet** [comment]
I haven’t had the chance to change it yet, but it’s an easy change.

**Comment by ercore** [comment]
Okay. Then I will put this issue in In Progress until it's changed/updated.

**Comment by tschet** [comment]
Is now wider

**Comment by ercore** [comment]
This has been resolved.
